In [3]:
import numpy as np
from numpy.linalg import norm
from numpy import dot

s1 = np.array([1, 0, 1])
s2 = np.array([0, 1, 1])

dot(s1, s2) / (norm(s1) * norm(s2))

np.float64(0.4999999999999999)

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

s1 = np.array([[1, 0, 1]])
s2 = np.array([[0, 1, 1]])

cosine_similarity(s1, s2)

array([[0.5]])

In [ ]:
# %pip install kiwipiepy

In [6]:
%pip install pandas sqlalchemy psycopg2-binary python-dotenv

Requirement already satisfied: pandas in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (2.3.3)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp310-cp310-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: python-dotenv in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (1.2.1)
Requirement already satisfied: numpy>=1.22.4 in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (from pandas) (2026.1)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.4.0-cp310-cp310-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading sqlalchemy-2.0.49-cp310-cp310-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 20.0 MB/s  0:00:00
Using cached psycopg2_binary-2.9.12-cp310-cp310-win_amd64.whl (2.8 MB)
Using cached greenlet-3.4.0-cp310-cp310-win_amd64.whl (237 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy

   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.4.0 psycopg2-binary-2.9.12 sqlalchemy-2.0.49
Note: you may need to restart the kernel to use updated packages.

In [7]:
import os
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv

# 1. .env 파일 로드
load_dotenv()

# 2. 환경 변수에서 DB 정보 가져오기
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")

# 3. PostgreSQL 연결 URL 생성
# 형식: postgresql://사용자:비밀번호@호스트:포트/데이터베이스
db_url = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# 4. 엔진 생성 및 데이터 불러오기
engine = create_engine(db_url)

query = "SELECT * FROM tbl_advertisement"
df = pd.read_sql(query, engine)

df

      id                   title                                            content  rate
0      1             최신형 스마트폰 할인        지금 구매하시면 최신형 스마트폰을 30% 할인된 가격에 만나보실 수 있습니다.   4.5
1      2              유기농 강아지 사료     우리 아이를 위한 건강한 선택, 100% 유기농 성분으로 만든 프리미엄 사료입니다.   4.8
2      3           직장인 맞춤 재테크 강의             월급 관리부터 주식 투자까지, 전문가가 알려주는 실전 재테크 노하우.   4.2
3      4           제주도 3박 4일 패키지            푸른 바다와 함께하는 힐링 여행, 전 일정 숙박 및 항공권 포함 특가.   3.9
4      5            고수분 히알루론산 크림                건조한 피부에 즉각적인 수분을 공급하는 저자극 보습 크림입니다.   4.7
..   ...                     ...                                                ...   ...
495  496      초정밀 인공지능 기반 펀드 셀렉터        수천 개의 펀드 중 우수한 성과를 낼 상품을 AI가 자동 선별하여 추천합니다.   4.9
496  497     지능형 자동 금융 자산 백업 서비스   해킹이나 사고에 대비해 자산 정보를 안전하게 보호하는 AI 기반의 자동화 보안 솔루션.   4.7
497  498     AI 기반 디지털 자산 지갑 자동화        복잡한 주소나 키 관리 없이 AI가 안전하게 자산을 보관하고 전송해 드립니다.   4.8
498  499    스마트 지능형 금융 목표 달성 가이드  내 집 마련, 차 구매 등 목표를 설정하면 AI가 자동으로 저축 계획을 짜고 관리합니다.   4.9
499  500  혁신적 AI 기반 자산 최적화 토탈 케어           자산의 시작부터 끝까지 AI 자동화가 책임지는 가장 완벽한 금융 파트너.   5.0

[500 rows x 4 columns]

In [13]:
pre_df = (df.title + " " + df.content).to_frame('contents')
pre_df

                                              contents
0    최신형 스마트폰 할인 지금 구매하시면 최신형 스마트폰을 30% 할인된 가격에 만나보...
1    유기농 강아지 사료 우리 아이를 위한 건강한 선택, 100% 유기농 성분으로 만든 ...
2    직장인 맞춤 재테크 강의 월급 관리부터 주식 투자까지, 전문가가 알려주는 실전 재테...
3    제주도 3박 4일 패키지 푸른 바다와 함께하는 힐링 여행, 전 일정 숙박 및 항공권...
4     고수분 히알루론산 크림 건조한 피부에 즉각적인 수분을 공급하는 저자극 보습 크림입니다.
..                                                 ...
495  초정밀 인공지능 기반 펀드 셀렉터 수천 개의 펀드 중 우수한 성과를 낼 상품을 AI...
496  지능형 자동 금융 자산 백업 서비스 해킹이나 사고에 대비해 자산 정보를 안전하게 보...
497  AI 기반 디지털 자산 지갑 자동화 복잡한 주소나 키 관리 없이 AI가 안전하게 자...
498  스마트 지능형 금융 목표 달성 가이드 내 집 마련, 차 구매 등 목표를 설정하면 A...
499  혁신적 AI 기반 자산 최적화 토탈 케어 자산의 시작부터 끝까지 AI 자동화가 책임...

[500 rows x 1 columns]

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_v = CountVectorizer()
count_matrix = count_v.fit_transform(pre_df.contents)

cosine = cosine_similarity(count_matrix)
print(cosine.shape)

(500, 500)

In [36]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

ad_contents = "나만을 위한 맞춤형 인공지능 자산 관리 솔루션, \
에이아이 웰스 복잡한 금융 데이터와 시장의 흐름을 초정밀 AI가 실시간으로 분석합니다. \
당신의 투자 성향과 목표에 최적화된 포트폴리오를 제공하여 안전하고 효율적인 자산 증식을 도와드립니다. \
지금 전문가 수준의 금융 자문을 경험해 보세요."

count_v = CountVectorizer()
count_matrix = count_v.fit_transform(pre_df.contents)
new_ad_matrix = count_v.transform([ad_contents])

sim_scores = cosine_similarity(new_ad_matrix, count_matrix)
sim_indices = sim_scores.argsort()[0][::-1][:5]
sim_ads = df.iloc[sim_indices]

sim_ids = sim_ads['id'].values
sim_rates = sim_ads['rate'].values
new_ad_sim_scores = sim_scores[0][sim_indices]

# 가중 평균 계산(유사도가 높은 애들에 가중치를 더 많이 줌)
# 유사도가 낮은 데이터의 평점이 결과값에 끼치는 영향력을 약하게 만들기 위해서 사용함.
predicted_rate = np.dot(new_ad_sim_scores, sim_rates) / new_ad_sim_scores.sum()

print(f"가장 유사한 광고 ID: {sim_ids}")
print(f"상위 5개 유사도 점수: {new_ad_sim_scores}")
print(f"예상 평점: {predicted_rate:.2f}")

가장 유사한 광고 ID: [477 422 401 495 445]
상위 5개 유사도 점수: [0.41695392 0.4152274  0.40533961 0.40522045 0.40522045]
예상 평점: 4.84

### Kiwi

In [37]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from kiwipiepy import Kiwi

kiwi = Kiwi()
josa_tags = ["JKS","JKC","JKO","JKG","JKB","JKV","JKQ","JX","JC",
            "EC","EF","EP","ETN","ETM"]

def removes_josa(sentence):
    result = []
    for token in kiwi.tokenize(sentence):
        if token.tag in josa_tags:
            continue

        result.append(token.lemma)
    return " ".join(result)


# 단어를 아주 잘게 쪼개기 때문에,
# 키워드가 직접 없어도 의미적 요소가 겹치는 광고까지 넒게 봄
pre_df.contents = pre_df.contents.apply(removes_josa)
pre_df

                                              contents
0    최신 형 스마트폰 할인 지금 구매 하 최신 형 스마트폰 30 % 할인 되 가격 만나...
1    유기농 강아지 사료 우리 아이 위하다 건강 하 선택 , 100 % 유기농 성분 만들...
2    직장인 맞춤 재테크 강의 월급 관리 주식 투자 , 전문가 알리다 주다 실전 재테크 ...
3    제주도 3 박 4 일 패키지 푸르다 바다 함께 하다 힐링 여행 , 전 일정 숙박 및...
4    고 수분 히알루론산 크림 건조 하 피부 즉각 적 이다 수분 공급 하 저 자극 보습 ...
..                                                 ...
495  초 정밀 인공 지능 기반 펀드 셀렉터 수천 개 펀드 중 우수 하 성과 내다 상품 A...
496  지능 형 자동 금융 자산 백업 서비스 해킹 사고 대비 하 자산 정보 안전 하 보호 ...
497  AI 기반 디지털 자산 지갑 자동 화 복잡 하 주소 키 관리 없이 AI 안전 하 자...
498  스마트 지능 형 금융 목표 달성 가이드 나 집 마련 , 차 구매 등 목표 설정 하 ...
499  혁신 적 AI 기반 자산 최적 화 토탈 케어 자산 시작 끝 AI 자동 화 책임지다 ...

[500 rows x 1 columns]

In [38]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

ad_contents = "나만을 위한 맞춤형 인공지능 자산 관리 솔루션, \
에이아이 웰스 복잡한 금융 데이터와 시장의 흐름을 초정밀 AI가 실시간으로 분석합니다. \
당신의 투자 성향과 목표에 최적화된 포트폴리오를 제공하여 안전하고 효율적인 자산 증식을 도와드립니다. \
지금 전문가 수준의 금융 자문을 경험해 보세요."

ad_contents = removes_josa(ad_contents)

count_v = CountVectorizer()
count_matrix = count_v.fit_transform(pre_df.contents.apply(removes_josa))
new_ad_matrix = count_v.transform([ad_contents])

sim_scores = cosine_similarity(new_ad_matrix, count_matrix)
sim_indices = sim_scores.argsort()[0][::-1][:5]
sim_ads = df.iloc[sim_indices]

sim_ids = sim_ads['id'].values
sim_rates = sim_ads['rate'].values
new_ad_sim_scores = sim_scores[0][sim_indices]

# 가중 평균 계산(유사도가 높은 애들에 가중치를 더 많이 줌)
# 유사도가 낮은 데이터의 평점이 결과값에 끼치는 영향력을 약하게 만들기 위해서 사용함.
predicted_rate = np.dot(new_ad_sim_scores, sim_rates) / new_ad_sim_scores.sum()

print(f"가장 유사한 광고 ID: {sim_ids}")
print(f"상위 5개 유사도 점수: {new_ad_sim_scores}")
print(f"예상 평점: {predicted_rate:.2f}")

가장 유사한 광고 ID: [401 450 406 422 482]
상위 5개 유사도 점수: [0.61105238 0.48769207 0.47739604 0.45749571 0.45517926]
예상 평점: 4.86

In [39]:
# %pip install konlpy

Collecting konlpy
  Using cached konlpy-0.6.0-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting JPype1>=0.7.0 (from konlpy)
  Using cached jpype1-1.7.0-cp310-cp310-win_amd64.whl.metadata (4.6 kB)
Requirement already satisfied: lxml>=4.1.0 in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (from konlpy) (6.1.0)
Requirement already satisfied: numpy>=1.6 in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (from konlpy) (2.2.6)
Requirement already satisfied: packaging in c:\programdata\anaconda3\envs\machine-learning\lib\site-packages (from JPype1>=0.7.0->konlpy) (26.0)
Using cached konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
Using cached jpype1-1.7.0-cp310-cp310-win_amd64.whl (357 kB)
Installing collected packages: JPype1, konlpy

   ---------------------------------------- 0/2 [JPype1]
   -------------------- ------------------- 1/2 [konlpy]
   ---------------------------------------- 2/2 [konlpy]

Successfully installed JPype1-1.7.0 konlpy-0.6.0
Note: you may need to restart the kernel to use updated packages.

In [42]:
from konlpy.tag import Okt

okt = Okt()

okt.nouns("고구마는 맛있어. 자동차는 빨라. 안녕하세요 반갑습니다.")

['고구마', '자동차']

In [46]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from konlpy.tag import Okt

ad_contents = "나만을 위한 맞춤형 인공지능 자산 관리 솔루션, \
에이아이 웰스 복잡한 금융 데이터와 시장의 흐름을 초정밀 AI가 실시간으로 분석합니다. \
당신의 투자 성향과 목표에 최적화된 포트폴리오를 제공하여 안전하고 효율적인 자산 증식을 도와드립니다. \
지금 전문가 수준의 금융 자문을 경험해 보세요."

ad_contents = " ".join(okt.nouns(ad_contents))

count_v = CountVectorizer()
count_matrix = count_v.fit_transform(pre_df.contents.apply(lambda x: " ".join(okt.nouns(x))))
new_ad_matrix = count_v.transform([ad_contents])

sim_scores = cosine_similarity(new_ad_matrix, count_matrix)
sim_indices = sim_scores.argsort()[0][::-1][:5]
sim_ads = df.iloc[sim_indices]

sim_ids = sim_ads['id'].values
sim_rates = sim_ads['rate'].values
new_ad_sim_scores = sim_scores[0][sim_indices]

# 가중 평균 계산(유사도가 높은 애들에 가중치를 더 많이 줌)
# 유사도가 낮은 데이터의 평점이 결과값에 끼치는 영향력을 약하게 만들기 위해서 사용함.
predicted_rate = np.dot(new_ad_sim_scores, sim_rates) / new_ad_sim_scores.sum()

print(f"가장 유사한 광고 ID: {sim_ids}")
print(f"상위 5개 유사도 점수: {new_ad_sim_scores}")
print(f"예상 평점: {predicted_rate:.2f}")

df.iloc[sim_ids]

가장 유사한 광고 ID: [401 482 406 450 454]
상위 5개 유사도 점수: [0.57394404 0.49135381 0.46534004 0.46534004 0.43643578]
예상 평점: 4.88

      id               title                                            content  rate
401  402   알고리즘 기반 자동 매매 시스템  감정을 배제한 데이터 중심의 퀀트 알고리즘이 24시간 시장을 감시하며 최적의 타이밍...   4.8
482  483  초정밀 금융 알고리즘 튜닝 서비스      나만의 투자 철학을 AI가 자동 학습하여 전용 자동화 시스템으로 만들어 드립니다.   4.8
406  407   로보어드바이저 자산 관리의 정점  복잡한 계산은 AI에게 맡기세요. 실시간 금융 자동화 기술이 선사하는 압도적인 자산...   5.0
450  451   스마트 크라우드 펀딩 자동 투자      검증된 프로젝트를 AI가 자동 선별하여 소액으로도 가능한 분산 투자 금융 시스템.   4.9
454  455    초정밀 지수 추종 자동화 엔진    S&P 500 등 주요 지수를 완벽하게 추종하며 비용을 최소화하는 AI 금융 솔루션.   4.7

### TFIDF
- TF(Term Frequency): 의미가 뚜렷한 단어의 가중치를 높여줌
- IDF(Inverse Document Frequency): 모든 문서에서 흔하게 나오는 단어는 점수를 깎음

In [48]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

ad_contents = "나만을 위한 맞춤형 인공지능 자산 관리 솔루션, \
에이아이 웰스 복잡한 금융 데이터와 시장의 흐름을 초정밀 AI가 실시간으로 분석합니다. \
당신의 투자 성향과 목표에 최적화된 포트폴리오를 제공하여 안전하고 효율적인 자산 증식을 도와드립니다. \
지금 전문가 수준의 금융 자문을 경험해 보세요."

ad_contents = removes_josa(ad_contents)

tfidf_v = TfidfVectorizer()
tfidf_matrix = tfidf_v.fit_transform(pre_df.contents.apply(removes_josa))
new_ad_matrix = tfidf_v.transform([ad_contents])

sim_scores = cosine_similarity(new_ad_matrix, tfidf_matrix)
sim_indices = sim_scores.argsort()[0][::-1][:5]
sim_ads = df.iloc[sim_indices]

sim_ids = sim_ads['id'].values
sim_rates = sim_ads['rate'].values
new_ad_sim_scores = sim_scores[0][sim_indices]

# 가중 평균 계산(유사도가 높은 애들에 가중치를 더 많이 줌)
# 유사도가 낮은 데이터의 평점이 결과값에 끼치는 영향력을 약하게 만들기 위해서 사용함.
predicted_rate = np.dot(new_ad_sim_scores, sim_rates) / new_ad_sim_scores.sum()

print(f"가장 유사한 광고 ID: {sim_ids}")
print(f"상위 5개 유사도 점수: {new_ad_sim_scores}")
print(f"예상 평점: {predicted_rate:.2f}")

df.iloc[sim_ids]

가장 유사한 광고 ID: [401 406 482 450 422]
상위 5개 유사도 점수: [0.50210505 0.44139482 0.29160572 0.28918148 0.27921334]
예상 평점: 4.86

      id               title                                            content  rate
401  402   알고리즘 기반 자동 매매 시스템  감정을 배제한 데이터 중심의 퀀트 알고리즘이 24시간 시장을 감시하며 최적의 타이밍...   4.8
406  407   로보어드바이저 자산 관리의 정점  복잡한 계산은 AI에게 맡기세요. 실시간 금융 자동화 기술이 선사하는 압도적인 자산...   5.0
482  483  초정밀 금융 알고리즘 튜닝 서비스      나만의 투자 철학을 AI가 자동 학습하여 전용 자동화 시스템으로 만들어 드립니다.   4.8
450  451   스마트 크라우드 펀딩 자동 투자      검증된 프로젝트를 AI가 자동 선별하여 소액으로도 가능한 분산 투자 금융 시스템.   4.9
422  423    실시간 외환 거래 자동화 로봇  변동성 큰 외환 시장을 24시간 감시하고 AI가 자동 대응하여 안정적인 수익을 창출...   4.9

In [49]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from konlpy.tag import Okt

ad_contents = "나만을 위한 맞춤형 인공지능 자산 관리 솔루션, \
에이아이 웰스 복잡한 금융 데이터와 시장의 흐름을 초정밀 AI가 실시간으로 분석합니다. \
당신의 투자 성향과 목표에 최적화된 포트폴리오를 제공하여 안전하고 효율적인 자산 증식을 도와드립니다. \
지금 전문가 수준의 금융 자문을 경험해 보세요."

ad_contents = " ".join(okt.nouns(ad_contents))

tfidf_v = TfidfVectorizer()
tfidf_matrix = tfidf_v.fit_transform(pre_df.contents.apply(lambda x: " ".join(okt.nouns(x))))
new_ad_matrix = tfidf_v.transform([ad_contents])

sim_scores = cosine_similarity(new_ad_matrix, tfidf_matrix)
sim_indices = sim_scores.argsort()[0][::-1][:5]
sim_ads = df.iloc[sim_indices]

sim_ids = sim_ads['id'].values
sim_rates = sim_ads['rate'].values
new_ad_sim_scores = sim_scores[0][sim_indices]

# 가중 평균 계산(유사도가 높은 애들에 가중치를 더 많이 줌)
# 유사도가 낮은 데이터의 평점이 결과값에 끼치는 영향력을 약하게 만들기 위해서 사용함.
predicted_rate = np.dot(new_ad_sim_scores, sim_rates) / new_ad_sim_scores.sum()

print(f"가장 유사한 광고 ID: {sim_ids}")
print(f"상위 5개 유사도 점수: {new_ad_sim_scores}")
print(f"예상 평점: {predicted_rate:.2f}")

df.iloc[sim_ids]

가장 유사한 광고 ID: [401 406 482 450 405]
상위 5개 유사도 점수: [0.43854216 0.43422583 0.32781666 0.27689967 0.25951178]
예상 평점: 4.85

      id               title                                            content  rate
401  402   알고리즘 기반 자동 매매 시스템  감정을 배제한 데이터 중심의 퀀트 알고리즘이 24시간 시장을 감시하며 최적의 타이밍...   4.8
406  407   로보어드바이저 자산 관리의 정점  복잡한 계산은 AI에게 맡기세요. 실시간 금융 자동화 기술이 선사하는 압도적인 자산...   5.0
482  483  초정밀 금융 알고리즘 튜닝 서비스      나만의 투자 철학을 AI가 자동 학습하여 전용 자동화 시스템으로 만들어 드립니다.   4.8
450  451   스마트 크라우드 펀딩 자동 투자      검증된 프로젝트를 AI가 자동 선별하여 소액으로도 가능한 분산 투자 금융 시스템.   4.9
405  406     지능형 개인 맞춤 포트폴리오  AI가 당신의 투자 성향을 완벽 분석하여 전 세계 자산에 분산 투자하는 자동 최적화...   4.8

$$\text{예상 평점} = \frac{\sum (\text{유사도} \times \text{평점})}{\sum \text{유사도}}$$